### ISSUE TITLE
External access

### ISSUE THREAD

**Issue by mcbain** [leportlabs/mongo-k8s-sidecar#2]
Is there a way to access the single mongo instances externally somehow?
Maybe using the kube-proxy or a service?

**Comment by cvallance** [comment]
IIRC, the only way to access anything inside a kubernetes cluster from outside is via a service. You'd also have to set it up in a way that each mongo instance inside kubernetes could be associated with its own service... basically means they'd have to have their own replication controller with different labels.

This is assuming you/d be using kuberenetes conventions to access the mongo instances. You might be able to dream up anther way by going directly through the docker hosts or something similar.

Regardless, I think this is more of a kubernetes question rather than an issue with this project. I'm happy to keep discussing but I'm closing this issue.
